export default {
  FETCH_MOVIE: 'FETCH_MOVIE',
  FETCH_MOVIE_SUCCESS:'FETCH_MOVIE_SUCCESS',
  FETCH_MOVIE_FAILURE:'FETCH_MOVIE_FAILURE',
  FETCH_MOVIE_RESET:'FETCH_MOVIE_RESET',

  FETCH_PEOPLE_IN_MOVIE:"FETCH_PEOPLE_IN_MOVIE",
  FETCH_PEOPLE_IN_MOVIE_SUCCESS:"FETCH_PEOPLE_IN_MOVIE_SUCCESS",
  FETCH_PEOPLE_IN_MOVIE_FAILURE:"FETCH_PEOPLE_IN_MOVIE_FAILURE",
  FETCH_PEOPLE_IN_MOVIE_RESET:"FETCH_PEOPLE_IN_MOVIE_RESET",

  FETCH_PEOPLES:"FETCH_PEOPLES",
  FETCH_PEOPLES_SUCCESS:"FETCH_PEOPLES_SUCCESS",
  FETCH_PEOPLES_FAILURE:"FETCH_PEOPLES_FAILURE",
  FETCH_PEOPLES_RESET:"FETCH_PEOPLES_RESET"
}
